services:
    app:
        build: .
        restart: unless-stopped
        volumes:
            - .:/var/www
            - /var/www/vendor
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - 33061:3306
